version: '2'
services:
  edr-static:
    build:
      dockerfile: Dockerfile
    command: sh -c "nodemon --exec jspm run server.js"
    ports:
      - 8000:80
    environment:
      GRAPHQL_URL: "http://edr-graphql/"
      ELASTIC_URL: "http://edr.data-gov-ua.org:9200"
    volumes:
      - .:/src/
      - ./tmp/node_modules/:/src/node_modules
      - ./tmp/npm_cache/:/root/.npm/
      - ./tmp/jspm_cache/:/root/.jspm/
      - ./tmp/tmp/:/tmp/
  edr-watch:
    build:
      dockerfile: Dockerfile
      context: .
    command: sh -c 'npm install && jspm install && jspm bundle browser.js -wid'
    volumes:
      - .:/src/
      - ./tmp/node_modules/:/src/node_modules/
      - ./tmp/npm_cache/:/root/.npm/
      - ./tmp/jspm_cache/:/root/.jspm/
      - ./tmp/tmp/:/tmp/
  edr-graphql:
    build: ../edrpou-graphql/build
    ports:
      - 85:80
    command: sh -c "npm install && npm start"
    environment:
      API_URL: "http://edr.data-gov-ua.org/api"
      ELASTIC_URL: "http://edr.data-gov-ua.org:9200"
    volumes:
      - ../edrpou-graphql:/src
